"""
Utility helpers for AgentIQ
"""

import time


def format_report(report_data: dict) -> str:
    """Format the complete report data into a downloadable Markdown string."""
    topic = report_data.get("topic", "Unknown Topic")
    meta = report_data.get("metadata", {})
    sections = report_data.get("sections", {})

    lines = [
        f"# AgentIQ Research Report",
        f"## Topic: {topic}",
        f"",
        f"**Generated:** {meta.get('timestamp', time.strftime('%Y-%m-%d %H:%M'))}",
        f"**Research Depth:** {meta.get('depth', 'Standard')}",
        f"**Focus Areas:** {', '.join(meta.get('focus', ['General']))}",
        f"**Agents Used:** {meta.get('agents_used', 4)} AI Agents",
        f"",
        "---",
        "",
    ]

    if sections.get("plan"):
        lines += ["## 🗺️ Research Plan", "", sections["plan"], "", "---", ""]

    if sections.get("research"):
        lines += ["## 🔍 Research Findings", "", sections["research"], "", "---", ""]

    if sections.get("analysis"):
        lines += ["## 🧠 Analysis & Insights", "", sections["analysis"], "", "---", ""]

    if sections.get("report"):
        lines += ["## 📄 Final Report", "", sections["report"], "", "---", ""]

    lines += [
        "",
        "---",
        "*Generated by AgentIQ — Multi-Agent AI Research Assistant*",
        "*Built with Python, Streamlit & Anthropic Claude API*",
        "*CSE435 Comprehensive Seminar Project*",
    ]

    return "\n".join(lines)


def get_topic_suggestions() -> list:
    """Return a list of trending CSE/AI topics for 2026–27."""
    return [
        "Agentic AI Systems",
        "LLM Memory Architecture",
        "Quantum ML Algorithms",
        "AI in Cybersecurity",
        "Edge AI & TinyML",
        "Multimodal Foundation Models",
        "AI Ethics & Governance",
        "RAG vs Fine-tuning",
    ]


def truncate_text(text: str, max_chars: int = 200) -> str:
    """Truncate text for display purposes."""
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "..."


def sanitize_filename(name: str) -> str:
    """Create a safe filename from a topic string."""
    import re
    safe = re.sub(r'[^\w\s-]', '', name)
    safe = re.sub(r'\s+', '_', safe.strip())
    return safe[:50]
